# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d6dd451036c4cb3fa711169742477792541af1a4e3c30863b6cc7a038a1ea8e048ef0a2e6f778f5ee259e5735aa1e658aab3ec856d1afd805aa470f50f21934

test:
  secret_key_base: 3cba04f555c536c259020856797c6362ff51b50bd30a2aad6e4a5e42fc2ce7b7677e824bad07c5d4a7b10b12d44378aac5a4492c55ad16d48544c7dc32ef470b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
